#
#
#COPYRIGHT JAMES CONWAY (615283) 2018 (C)
#This code is mine and is not to be used for any personal or other gain.
#If you wish to fork off of this GitHub page, feel free but you MUST keep my Copyright notices and name in the code where it is now.
#If you compile this code, even if you have edited it, do not share it with others on Bukkit and Spigot, keep it to GitHub.
#
#

name: BetterWarnings
main: com.georlegacy.general.betterwarnings.MainClass
author: 615283
version: 2.1.6
description: Allows staff to warn players.
commands:
    warn:
        description: Assigns a warning to a player
        usage: /<command> <playername> <warning>
        aliases: warnplayer
    warnings:
        description: Counts the warnings of a player
        usage: /<command> <playername>
        aliases: [countwarnings, warns]
    listwarnings:
        description: Lists the warnings of a player
        usage: /<command> <playername>
        aliases: listwarns
    clearwarnings:
        description: Clears all warnings currently assigned to a player
        usage: /<command> <playername>
        aliases: clearwarns
    clearwarning:
        description: Clears a single warning of a player, add -s to suppress notification to player
        usage: /<command> <playername> <warningnumber> [-s]
        aliases: clearwarn
    betterwarnings:
        description: Plugin info & help
        usage: /<command>
        aliases: [bw, bwarn, bwarnings]
permissions:
    betterwarnings.*:
        description: Gives access to all commands from the BetterWarnings plugin
        children:
            betterwarnings.warn: true
            betterwarnings.viewwarns: true
            betterwarnings.clearwarns: true
            betterwarnings.clearwarn: true
        default: op
    betterwarnings.warn:
        description: Allows a player to assign warnings to other players
        default: false
    betterwarnings.viewwarns: 
        description: Allows a player to view warnings currently assigned to a player
        default: false
    betterwarnings.clearwarns:
        description: Allows a player to clear ALL warnings of another player
        default: false
        children:
            betterwarnings.viewwarns: true
            betterwarnings.clearwarn: true
    betterwarnings.clearwarn:
        description: Allows a single warning at a time from a player
        default: false
        children:
            betterwarnings.viewwarns: true